use Test_DB
GO

SELECT @@SERVERNAME;

SELECT * FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME = 'Customer_shopping_behaviour';

select * from Customer_shopping_behaviour
where size ='L' AND payment_method IN( 'Cash', 'Venmo');


--- What is the total revenue generated by male vs female customers
select sum(purchase_amount) as Total_revenue, gender
from Customer_shopping_behaviour
group by gender


---  Which customers used a discount but still spent more than the average purchase amount
select  customer_id, purchase_amount FROM Customer_shopping_behaviour
where discount_applied = 'Yes' AND Purchase_amount >= (select AVG(Purchase_amount) FROM Customer_shopping_behaviour)


--- which are the top 5 products  with highest average review rating
select TOP(10) item_purchased, ROUND(AVG(review_rating),2) as  highestReviewRating
from Customer_shopping_behaviour
group by item_purchased 
order by highestReviewRating DESC

--- Compare the average purchase Amounts between standard and express shipping
select shipping_type, avg(purchase_amount) as 'average purchase amount' from Customer_shopping_behaviour
group by shipping_type
Having shipping_type in ('Standard','Express')

--- Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers
select subscription_status, 
	count(customer_id)totalCustomer,
	round(avg(purchase_amount),4) averageSpent, 
	sum(purchase_amount) totalRevenue 
from Customer_shopping_behaviour
group by subscription_status

--- Which 5 products were most often bought at a discount
select top(5) item_purchased, 
	count(frequency_of_purchases) as 'frequency of purchases'
from Customer_shopping_behaviour
group by item_purchased, discount_applied
having discount_applied ='Yes'

---  which 5 products have the highest percentage of purchases with discounts applied?
select top(5) item_purchased, 
	round(100 * sum(case when discount_applied = 'Yes' then 1 Else 0 End)/ Count(*) ,2) as discount_rate
from Customer_shopping_behaviour
group by item_purchased
order by discount_rate DESC

--- Segment customers into New, Returning and loyal based on their total
--- number of previous purchases, and show the count of each segment

with customer_type as (
	select customer_id, previous_purchases,
		CASE
			WHEN previous_purchases = 1 then 'New'
			WHEN previous_purchases between 2 and 10 then 'Returning'
			Else 'Loyal'
			End as customer_segment
	from Customer_shopping_behaviour)
select customer_segment, count(*) as 'Number of Customers'
from customer_type
group by customer_segment;


--- what are the top 3 most purchased products in each category
with item_counts as (
	select item_purchased, category,
	count(customer_id) as total_orders,
	ROW_NUMBER() OVER(PARTITION BY Category order by count(customer_id) DESC) as RankedItem
	from Customer_shopping_behaviour
	group by category, item_purchased)
select RankedItem, item_purchased, category, total_orders
from item_counts
where RankedItem <= 3;

--- Are the customers who repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
	count(customer_id) as repeat_buyers
from Customer_shopping_behaviour
where previous_purchases > 5
group by subscription_status

--- what is the revenue by age_group
select age_group, 
SUM(previous_purchases) as total_revenue
from Customer_shopping_behaviour
group by age_group
order by total_revenue;

---what are the top 5 most purchased products in each category by age_group

with items_count as (
	select age_group,
		item_purchased,
		category,
		count(customer_id) as total_orders,
		ROW_NUMBER() OVER( partition by category, age_group order by count(customer_id) desc) as Rank_items
	from Customer_shopping_behaviour
	group by age_group, item_purchased, category)
select Rank_items, category, age_group, item_purchased, total_orders
from items_count
where Rank_items <= 3;














































